app/models.py
#coding=utf-8
from datetime import datetime
from flask.ext.login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, login_manager
from markdown import markdown
import bleach


"""
u = User(email='me@kweima.com', username='kweima', password='123')
"""


class User(UserMixin, db.Model):

	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key = True)
	email = db.Column(db.String(64), unique = True, index = True)
	username = db.Column(db.String(64), unique = True, index = True)
	password_hash = db.Column(db.String(128))
	posts = db.relationship('Post', backref = 'author', lazy = 'dynamic')

	# 创建只写属性
	@property
	def password(self):
		raise AttributeError('<password> is not a readable attribute!')

	# 写密码时生成哈希值
	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	# 验证密码
	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)


class Post(db.Model):

	__tablename__ = 'posts'
	id = db.Column(db.Integer, primary_key = True)
	title = db.Column(db.String(128), nullable = False)
	content = db.Column(db.Text)
	content_html = db.Column(db.Text)
	excerpt = db.Column(db.Text)
	status = db.Column(db.String(64))
	timestamp = db.Column(db.DateTime, index = True, default = datetime.utcnow)
	author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

	@staticmethod
	def on_changed_content(target, value, oldvalue, initiator):
		allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'h4', 'h5', 'p']
		target.content_html = bleach.linkify(bleach.clean(
        	markdown(value, output_format='html'), 
        	tags=allowed_tags, strip=True))


db.event.listen(Post.content, 'set', Post.on_changed_content)


@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

app/panel/forms.py
from datetime import datetime
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextAreaField, DateTimeField, SelectField
from wtforms.validators import Required, Length
from flask.ext.pagedown.fields import PageDownField


class PostForm(Form):
	title = StringField('Title', validators = [Required(), Length(1, 128)])
	content = PageDownField('Content')
	# full format : %Y-%m-%dT%H:%M:%S.%LZ
	timestamp = DateTimeField('Date time', format = '%Y-%m-%d %H:%M:%S', default = datetime.utcnow())
	status = SelectField('Status', coerce=int, choices=[(1, 'Foo 1'), (2, 'Foo 2')])
	submit = SubmitField('Submit')
	save = SubmitField('Save')
	discard = SubmitField('Discard')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
from flask.ext.login import LoginManager
from flask.ext.pagedown import PageDown

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/auth')

    from .panel import panel as panel_blueprint
    app.register_blueprint(panel_blueprint, url_prefix = '/panel')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, current_app
from . import main
from ..models import Post

@main.route('/')
def index():
	page = request.args.get('page', 1, type = int)
	pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page = current_app.config['BLOG_POSTS_PER_PAGE'], error_out = False)
	posts = pagination.items
	#posts = Post.query.order_by(Post.timestamp.desc()).all()
	return render_template('main/index.html', posts = posts, pagination = pagination, single_post = False)


@main.route('/post/<int:id>')
def post(id):
	post = Post.query.get_or_404(id)
	return render_template('main/post.html', post = post, single_post = True)

app/panel/__init__.py
from flask import Blueprint

panel = Blueprint('panel', __name__)

from . import views

app/panel/views.py
from flask import render_template, flash, redirect, url_for, request, current_app
from . import panel
from flask.ext.login import login_required, current_user
from ..models import Post
from .forms import PostForm
from .. import db


@panel.route('/')
@login_required
def index():
	return render_template('panel/index.html')


@panel.route('/edit_post', methods = ['GET', 'POST'])
@login_required
def edit_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(
			title = form.title.data,
			content = form.content.data,
			timestamp = form.timestamp.data,
			author_id = current_user.get_id(),
			author = current_user._get_current_object(),
			)
		db.session.add(post)
		return redirect(url_for('.index'))
		flash('Submited')
	return render_template('panel/edit_post.html', form = form)


@panel.route('/post_list', methods = ['GET', 'POST'])
@login_required
def post_list():
	if request.method == 'GET':
		page = request.args.get('page', 1, type = int)
		#pagination = Post.query.with_entities(Post.title, Post.timestamp).order_by(Post.timestamp.desc()).paginate(page, per_page = current_app.config['BLOG_POSTS_PER_PAGE'], error_out = False)
		pagination = Post.query.with_entities(Post.title, Post.timestamp).order_by(Post.timestamp.desc()).paginate(page, per_page = 1000, error_out = False)
		posts = pagination.items
		return render_template('panel/post_list.html', posts = posts, pagination = pagination, single_post = False)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css', _external=True) }}"/>
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon"/>
<link rel="icon" href="{{ url_for('static', filename = 'favicon.png') }}" type="image/x-icon"/>
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-1.11.2.min.js', _external=True) }}"></script>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_jquery() }}
{{ moment.include_moment() }}
{{ moment.lang(config['MOMENT_LOCAL_LANG']) }}
{% endblock %}

{% block body %}
<div class="outer-wrapper">
{{ super() }}
</div>
{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}

app/templates/main/blog_post.html
<div class="blog-post">
	<div class="blog-post-title">
		<h3>
		{% if not single_post %}
			<a href="{{ url_for('.post', id=post.id) }}">{{ post.title }}</a>
		{% else %}
			{{ post.title }}
		{% endif %}
		</h3>
	</div>

	<div class="blog-post-content"><p>{{ post.content_html|safe }}</p></div>

	<div class="blog-post-footer">
		<div class="blog-post-timestamp">
			<span class="glyphicon glyphicon-time" aria-hidden="true"></span><span/>
			<span>{{ moment(post.timestamp).format("YYYY-MM-d hh:mm") }}</span>

			<span class="glyphicon glyphicon-user" aria-hidden="true"></span><span/>
			<span>{{ post.author.username|upper }}</span>
		</div>
	</div>
</div>

app/templates/main/index.html
{% extends "main/main_base.html" %}
{% import "_macros.html" as macros %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/responsive-paginate.js', _external=True) }}"></script>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
$(document).ready(function () {
    $(".pagination").rPage();
}); 
</script>
{% endblock %}

{% block blog_header %}

{% endblock %}

{% block blog_main %}

{% for post in posts %}
{% include "main/blog_post.html" %}
{% endfor %}

<div class="text-center">
    <div class="pagination">
        {{ macros.pagination_widget(pagination, '.index') }}
    </div>
</div>

{% endblock %}

app/templates/main/main_base.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">KWEIMA Blog</a> </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('panel.index') }}">Panel</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
{{ super() }}

{% block blog_header %}
{% endblock %}

{% block blog_main %}
{% endblock %}

{% block blog_sidebar %}
{% endblock %}
</div>
{% endblock %}

app/templates/main/post.html
{% extends "main/main_base.html" %}
{% import "main/_macros.html" as macros %}

{% block blog_header %}

{% endblock %}

{% block blog_main %}

{% include "main/blog_post.html" %}

{% endblock %}

app/templates/panel/edit_post.html
{% extends "panel/panel_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block scripts %}
{{ super( )}}
{{ pagedown.include_pagedown() }}
{% endblock %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="col-lg-12">
        <div class="page-header"><h3>Edit Post</h3></div>
    </div>
	<form method="post" role="form">
		<div class="col-lg-8">
			{{ form.hidden_tag() }}
        {{ wtf.form_field(form.title) }}
        {{ form.content.label }}
        {{ form.content(class="form-control", rows="12", style="resize:vertical")|safe }}
		</div>
        <div class="col-lg-4">
    	<!-- {{ wtf.form_field(form.timestamp) }} -->
    	{{ form.timestamp.label }}
    	{{ form.timestamp(class="form-control") }}
        {{ wtf.form_field(form.status) }}
        {{ form.submit(class="btn btn-primary") }}
        {{ form.save(class="btn btn-success") }}
        {{ form.discard(class="btn btn-danger") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/panel/index.html
{% extends "panel/panel_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{{ super() }}
<div class="container">
	<h1>Panel</h1>
</div>
{% endblock %}

app/templates/panel/panel_base.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/admin-style.css', _external=True) }}"/>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('panel.index') }}">Panel</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('panel.post_list') }}">Posts</a></li>
                <li><a href="{{ url_for('panel.edit_post') }}">New Post</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('main.index') }}">View Site</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/panel/post_list.html
{% extends "panel/panel_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}


{% block scripts %}
{{ super( )}}
{{ pagedown.include_pagedown() }}
{% endblock %}

{% block content %}
{{ super() }}
<div class="container">
    <div class="col-lg-12">
        <div class="page-header">
            <h3>Post List</h3>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th data-field="id">Title</th>
                            <th data-field="name">Time</th>
                        </tr>
                        {% for post in posts %}
                        <tr>
                            <td>{{ post.title }}</td>
                            <td>{{ post.timestamp }}</td>
                        </tr>
                        {% endfor %}
                    </thead>
                </table>
            </div>
        </div>

        <div class="text-center">
            <div class="pagination">
                {{ macros.pagination_widget(pagination, '.index') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}